const ACTIONS = {
    LOGIN: 'LOGIN',
    GET_TOKEN: 'GET_TOKEN',
    GET_USER: 'GET_USER',
    GET_ALL_USERS: 'GET_ALL_USERS',
    CREATE_COURSE: 'CREATE_COURSE',
    CREATE_QUIZ: 'CREATE_QUIZ',
    FETCH_ALL: 'FETCH_ALL',
    FETCH_ALL_QUIZ: 'FETCH_ALL_QUIZ',
    FETCH_ALL_COURSE_BY_USER:'FETCH_ALL_COURSE_BY_USER',
    FETCH_ALL_COURSE_BY_ID:'FETCH_ALL_COURSE_BY_ID',
    FETCH_ALL_COURSE_BY_CATEGORIE:'FETCH_ALL_COURSE_BY_CATEGORIE',
    UPDATE_COURSE: 'UPDATE_COURSE',
    DELETE_COURSE: 'DELETE_COURSE',
    DELETE_QUIZ: 'DELETE_QUIZ',
    CREATE_CATEGORIE: 'CREATE_CATEGORIE',
    FETCH_ALLCATEGORIE: 'FETCH_ALLCATEGORIE',
    UPDATE_CATEGORIE: 'UPDATE_CATEGORIE',
    DELETE_CATEGORIE: 'DELETE_CATEGORIE',
    FETCH_ALL_COURSE_BY_USER_PANIER: 'FETCH_ALL_COURSE_BY_USER_PANIER',
    CREATE_PANIER: 'CREATE_PANIER',
    DELETE_COURSE_FROM_PANIER: 'DELETE_COURSE_FROM_PANIER',
    DELETE_SUBSCRIBE: 'DELETE_SUBSCRIBE',
    CREATE_SUBSCRIBE: 'CREATE_SUBSCRIBE',
    FETCH_ALLSUBSCRIBES: 'FETCH_ALLSUBSCRIBES',
    FETCH_ALL_COURSE_BY_USER_for_PANIER: 'FETCH_ALL_COURSE_BY_USER_for_PANIER',
    CREATE_CERTIFICATION: 'CREATE_CERTIFICATION',
    

}

export default ACTIONS